#! /usr/bin/env python

from scapy.all import *
import time
import os
import logging

class InternetProtocolNumbers:
    ''' INTERNET PROTOCOL NUMBERS
        refenrence: RFC 790(Page 5)
        https://www.rfc-editor.org/rfc/rfc790.txt
    '''
    data = {
            0   : 'Reserved',
            1   : 'ICMP',
            2   : 'Unassigned',
            3   : 'Gateway-to-Gateway',
            4   : 'CMCC Gateway Monitoring Message',
            5   : 'ST',
            6   : 'TCP',
            7   : 'UCL',
            8   : 'Unassigned',
            9   : 'Secure',
            10  : 'BBN RCC Monitoring',
            11  : 'NVP',
            12  : 'PUP',
            13  : 'Pluribus',
            14  : 'Telenet',
            15  : 'XNET',
            16  : 'Chaos',
            17  : 'User Datagram',
            18  : 'Multiplexing',
            19  : 'DCN',
            20  : 'TAC Monitoring',
            21  : 'Unassigned',
            22  : 'Unassigned',
            23  : 'Unassigned',
            24  : 'Unassigned',
            25  : 'Unassigned',
            26  : 'Unassigned',
            27  : 'Unassigned',
            28  : 'Unassigned',
            29  : 'Unassigned',
            30  : 'Unassigned',
            31  : 'Unassigned',
            32  : 'Unassigned',
            33  : 'Unassigned',
            34  : 'Unassigned',
            35  : 'Unassigned',
            36  : 'Unassigned',
            37  : 'Unassigned',
            38  : 'Unassigned',
            39  : 'Unassigned',
            40  : 'Unassigned',
            41  : 'Unassigned',
            42  : 'Unassigned',
            43  : 'Unassigned',
            44  : 'Unassigned',
            45  : 'Unassigned',
            46  : 'Unassigned',
            47  : 'Unassigned',
            48  : 'Unassigned',
            49  : 'Unassigned',
            50  : 'Unassigned',
            51  : 'Unassigned',
            52  : 'Unassigned',
            53  : 'Unassigned',
            54  : 'Unassigned',
            55  : 'Unassigned',
            56  : 'Unassigned',
            57  : 'Unassigned',
            58  : 'Unassigned',
            59  : 'Unassigned',
            60  : 'Unassigned',
            61  : 'Unassigned',
            62  : 'Unassigned',
            63  : 'any local network',
            64  : 'SATNET and Backroom EXPAK',
            65  : 'MIT Subnet Support',
            66  : 'Unassigned',
            67  : 'Unassigned',
            68  : 'Unassigned',
            69  : 'SATNET Monitoring',
            70  : 'Unassigned',
            71  : 'Internet Packet Core Utility',
            72  : 'Unassigned',
            73  : 'Unassigned',
            74  : 'Unassigned',
            75  : 'Unassigned',
            76  : 'Backroom SATNET Monitoring',
            77  : 'Unassigned',
            78  : 'WIDEBAND Monitoring',
            79  : 'WIDEBAND EXPAK',
            80  : 'Unassigned',
            81  : 'Unassigned',
            82  : 'Unassigned',
            83  : 'Unassigned',
            84  : 'Unassigned',
            85  : 'Unassigned',
            86  : 'Unassigned',
            87  : 'Unassigned',
            88  : 'Unassigned',
            89  : 'Unassigned',
            90  : 'Unassigned',
            91  : 'Unassigned',
            92  : 'Unassigned',
            93  : 'Unassigned',
            94  : 'Unassigned',
            95  : 'Unassigned',
            96  : 'Unassigned',
            97  : 'Unassigned',
            98  : 'Unassigned',
            99  : 'Unassigned',
            100 : 'Unassigned',
            101 : 'Unassigned',
            102 : 'Unassigned',
            103 : 'Unassigned',
            104 : 'Unassigned',
            105 : 'Unassigned',
            106 : 'Unassigned',
            107 : 'Unassigned',
            108 : 'Unassigned',
            109 : 'Unassigned',
            110 : 'Unassigned',
            111 : 'Unassigned',
            112 : 'Unassigned',
            113 : 'Unassigned',
            114 : 'Unassigned',
            115 : 'Unassigned',
            116 : 'Unassigned',
            117 : 'Unassigned',
            118 : 'Unassigned',
            119 : 'Unassigned',
            120 : 'Unassigned',
            121 : 'Unassigned',
            122 : 'Unassigned',
            123 : 'Unassigned',
            124 : 'Unassigned',
            125 : 'Unassigned',
            126 : 'Unassigned',
            127 : 'Unassigned',
            128 : 'Unassigned',
            129 : 'Unassigned',
            130 : 'Unassigned',
            131 : 'Unassigned',
            132 : 'Unassigned',
            133 : 'Unassigned',
            134 : 'Unassigned',
            135 : 'Unassigned',
            136 : 'Unassigned',
            137 : 'Unassigned',
            138 : 'Unassigned',
            139 : 'Unassigned',
            140 : 'Unassigned',
            141 : 'Unassigned',
            142 : 'Unassigned',
            143 : 'Unassigned',
            144 : 'Unassigned',
            145 : 'Unassigned',
            146 : 'Unassigned',
            147 : 'Unassigned',
            148 : 'Unassigned',
            149 : 'Unassigned',
            150 : 'Unassigned',
            151 : 'Unassigned',
            152 : 'Unassigned',
            153 : 'Unassigned',
            154 : 'Unassigned',
            155 : 'Unassigned',
            156 : 'Unassigned',
            157 : 'Unassigned',
            158 : 'Unassigned',
            159 : 'Unassigned',
            160 : 'Unassigned',
            161 : 'Unassigned',
            162 : 'Unassigned',
            163 : 'Unassigned',
            164 : 'Unassigned',
            165 : 'Unassigned',
            166 : 'Unassigned',
            167 : 'Unassigned',
            168 : 'Unassigned',
            169 : 'Unassigned',
            170 : 'Unassigned',
            171 : 'Unassigned',
            172 : 'Unassigned',
            173 : 'Unassigned',
            174 : 'Unassigned',
            175 : 'Unassigned',
            176 : 'Unassigned',
            177 : 'Unassigned',
            178 : 'Unassigned',
            179 : 'Unassigned',
            180 : 'Unassigned',
            181 : 'Unassigned',
            182 : 'Unassigned',
            183 : 'Unassigned',
            184 : 'Unassigned',
            185 : 'Unassigned',
            186 : 'Unassigned',
            187 : 'Unassigned',
            188 : 'Unassigned',
            189 : 'Unassigned',
            190 : 'Unassigned',
            191 : 'Unassigned',
            192 : 'Unassigned',
            193 : 'Unassigned',
            194 : 'Unassigned',
            195 : 'Unassigned',
            196 : 'Unassigned',
            197 : 'Unassigned',
            198 : 'Unassigned',
            199 : 'Unassigned',
            200 : 'Unassigned',
            201 : 'Unassigned',
            202 : 'Unassigned',
            203 : 'Unassigned',
            204 : 'Unassigned',
            205 : 'Unassigned',
            206 : 'Unassigned',
            207 : 'Unassigned',
            208 : 'Unassigned',
            209 : 'Unassigned',
            210 : 'Unassigned',
            211 : 'Unassigned',
            212 : 'Unassigned',
            213 : 'Unassigned',
            214 : 'Unassigned',
            215 : 'Unassigned',
            216 : 'Unassigned',
            217 : 'Unassigned',
            218 : 'Unassigned',
            219 : 'Unassigned',
            220 : 'Unassigned',
            221 : 'Unassigned',
            222 : 'Unassigned',
            223 : 'Unassigned',
            224 : 'Unassigned',
            225 : 'Unassigned',
            226 : 'Unassigned',
            227 : 'Unassigned',
            228 : 'Unassigned',
            229 : 'Unassigned',
            230 : 'Unassigned',
            231 : 'Unassigned',
            232 : 'Unassigned',
            233 : 'Unassigned',
            234 : 'Unassigned',
            235 : 'Unassigned',
            236 : 'Unassigned',
            237 : 'Unassigned',
            238 : 'Unassigned',
            239 : 'Unassigned',
            240 : 'Unassigned',
            241 : 'Unassigned',
            242 : 'Unassigned',
            243 : 'Unassigned',
            244 : 'Unassigned',
            245 : 'Unassigned',
            246 : 'Unassigned',
            247 : 'Unassigned',
            248 : 'Unassigned',
            249 : 'Unassigned',
            250 : 'Unassigned',
            251 : 'Unassigned',
            252 : 'Unassigned',
            253 : 'Unassigned',
            254 : 'Unassigned',
            255 : 'Reserved'}

logger = logging.getLogger('main')
logging.basicConfig(format='%(levelname)s: %(message)s', level=logging.DEBUG)
logger.setLevel(logging.DEBUG)

def process(x):
    protocol = x[IP].proto
    src = x[IP].src
    dst = x[IP].dst

    logger.info(src + '\t->\t' + dst + '\t' +
            InternetProtocolNumbers.data[protocol])

def main():
    sniff(prn=lambda x: process(x), lfilter=lambda x: hasattr(x, 'type')
            and hex(x.type) == '0x800')

if __name__ == "__main__":
    logger.info('sniff packet......')
    main()

